%FASHION A MIMO toolbox fashion file.
%   FASHION includes various (recommended) graphics settings for the
%   MIMO toolbox such as colors, line styles and fonts settings. All the
%   objects are set on the root level. This allows you to have a unified
%   fashion-look of the Visual Layer and there's no need to set these
%   properties for each figure or object generated by the mimo toolbox.
%   If you want to have these settings to be the Matlab's defaults, copy
%   its content into the file called startup.m. On the UNIX platforms this
%   file should be located in $HOME/matlab/ directory.

%   Copyright 2001-2003 Kamil Anis, anisk@feld.cvut.cz
%   Dept. of Radioelectronics, 
%   Faculty of Electrical Engineering
%   Czech Technical University in Pragu
%   $Revision: 2.1 $  $Date: 2003/1/16 17:33:28 $
%   --
%   <additional stuff goes here>

set(0,'defaultTextFontName','Times');
set(0,'defaultAxesFontName','Times');
%set(0,'defaultTextFontSize',9)
set(0,'defaultFigureToolbar','none');
set(0,'defaultFigureNumberTitle','off');
%set(0,'defaultFigureToolbar','auto');
set(0,'defaultLineColor','black');
%set(0,'DefaultAxesColorOrder',[0 0 0;1 0 0;0 1 0;0 0 1]);
set(0,'DefaultAxesColorOrder',[0 0 0]);
set(0,'defaultFigureColor',[1 1 1]);
